-- Resource codes are now autogenerated (RES-<id, 6 digits>) and unique.
-- Backfill items that never got a manual code; hand-entered codes are kept.
-- The NOT EXISTS guard skips the (unlikely) case where someone already typed
-- the exact code another row would generate — better a NULL to fix by hand
-- than a failed migration.
UPDATE "Item" i
SET "code" = 'RES-' || lpad(i."id"::text, 6, '0')
WHERE i."code" IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM "Item" x WHERE x."code" = 'RES-' || lpad(i."id"::text, 6, '0')
  );
