export enum ProcurementOrderStatus {
  DRAFT = 'DRAFT',
  ORDERED = 'ORDERED',
  PENDING_FINANCE_APPROVAL = 'PENDING_FINANCE_APPROVAL',
  FINANCE_APPROVED = 'FINANCE_APPROVED',
  FINANCE_REJECTED = 'FINANCE_REJECTED',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
}
